#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -Eeuo pipefail
exec 1>&2

touch smarthost.env
chmod 600 smarthost.env

systemctl --user enable gitea.service
systemctl --user restart gitea.service
