#!/usr/bin/env python3

#
# Copyright (C) 2026
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os

import agent


ssh_port = os.environ["SSH_TCP_PORT"]
agent.assert_exp(
    agent.add_public_service(
        os.environ["MODULE_ID"],
        [f"{ssh_port}/tcp"],
        replace_ports=True,
    ),
    "Could not expose the Gitea SSH port in the node firewall.",
)
