#!/usr/bin/env python3

#
# Copyright (C) 2026
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os

import agent


agent.assert_exp(
    agent.remove_public_service(os.environ["MODULE_ID"]),
    "Could not remove the Gitea SSH service from the node firewall.",
)
