#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import os
import sys


ssh_port = os.environ.get("SSH_TCP_PORT", "")
configuration = {
    "host": os.environ.get("TRAEFIK_HOST", ""),
    "http2https": os.environ.get("TRAEFIK_HTTP2HTTPS") == "True",
    "lets_encrypt": os.environ.get("TRAEFIK_LETS_ENCRYPT") == "True",
    "ssh_port": int(ssh_port) if ssh_port.isdigit() else 0,
}

json.dump(configuration, fp=sys.stdout)
