name: "Clean up API JSON Schema docs"

on:
  delete:

jobs:
  build-apidoc:
    name: "Delete apidoc branch ${{ github.event.ref }}"
    uses: NethServer/ns8-github-actions/.github/workflows/clean-apidoc.yml@1f7be3c6e4791a978df9c0a0454e9a8fea8d211a # v1
