name: "Clean up registry"

on:
  delete:
  workflow_dispatch:

permissions:
  packages: write

jobs:
  delete_images:
    name: "Delete ghcr.io images ${{ github.event.ref }}"
    runs-on: ubuntu-latest
    environment: Registry
    steps:
      - uses: NethServer/ns8-github-actions/.github/actions/delete-image@1f7be3c6e4791a978df9c0a0454e9a8fea8d211a # v1
        with:
          images: "gitea-reworked"
          delete_image_token: ${{ secrets.IMAGES_CLEANUP_TOKEN }}
